VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "BinanceOp"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public stamp As Date
Public wallet As String
Public operation As String
Public acquired As Variant
Public spent As Variant
Public ticker As String
Public price As Variant
Public amount As Variant
Public charge As Variant
Public bnb_fee As Variant
Public note As String
Public id As String
